"""S&P 500 membership helpers. Symbols use Yahoo-style tickers (BRK.B)."""

from __future__ import annotations

# Highest-turnover names we always stream in S&P 500 mode (IBKR line-limit friendly).
LIQUID_SP500 = [
    "AAPL", "MSFT", "NVDA", "AMZN", "META", "GOOGL", "GOOG", "TSLA", "AVGO", "BRK.B",
    "JPM", "LLY", "V", "MA", "COST", "UNH", "NFLX", "XOM", "WMT", "JNJ",
    "PG", "HD", "ORCL", "ABBV", "BAC", "KO", "CRM", "CSCO", "AMD", "PEP",
    "MCD", "ABT", "DIS", "WFC", "GE", "CAT", "NOW", "QCOM", "TXN", "INTU",
    "AMAT", "ISRG", "VZ", "MS", "IBM", "AMGN", "PFE", "RTX", "HON", "GS",
    "PLTR", "AXP", "LOW", "UNP", "BLK", "T", "COP", "TMUS", "SCHW", "NKE",
    "C", "MU", "PGR", "MDT", "ADP", "DE", "BMY", "CMCSA", "CVX", "INTC",
    "BA", "PYPL", "GM", "F", "USB", "MO", "SO", "GILD", "MMM", "CVS",
    "COF", "TGT", "UPS", "FDX", "SLB", "OXY", "WBD", "DAL", "UAL", "AAL",
]

# Current-ish S&P 500 universe. Dotted class shares are converted for IBKR.
_SP500_TEXT = """
A AAPL ABBV ABNB ABT ACGL ACN ADBE ADI ADM ADP ADSK AEE AEP AES AFL
AIG AIZ AJG AKAM ALB ALGN ALL ALLE AMAT AMCR AMD AME AMGN AMP AMT AMZN
ANET AON AOS APA APD APH APTV ARE ATO AVB AVGO AVY AWK AXON AXP AZO
BA BAC BALL BAX BBWI BBY BDX BEN BF.B BG BIIB BIO BK BKNG BKR BLDR BLK
BMY BR BRK.B BRO BSX BWA BX BXP C CAG CAH CARR CAT CB CBOE CBRE CCI
CCL CDNS CDW CE CEG CF CFG CHD CHRW CHTR CI CINF CL CLX CMCSA CME CMG
CMI CMS CNC CNP COF COO COP COR COST CPAY CPB CPRT CPT CRL CRM CRWD
CSCO CSGP CSX CTAS CTRA CTSH CTVA CVS CVX D DAL DAY DD DE DELL DFS DG
DGX DHI DHR DIS DLR DLTR DOC DOV DOW DPZ DRI DTE DUK DVA DVN DXCM EA
EBAY ECL ED EFX EG EIX EL ELV EMR ENPH EOG EPAM EQIX EQR EQT ES ESS ETN
ETR EVRG EW EXC EXPD EXPE EXR F FANG FAST FCX FDS FDX FE FFIV FI FICO
FIS FITB FOX FOXA FRT FSLR FTNT FTV GD GDDY GEV GILD GIS GL GLW
GM GNRC GOOG GOOGL GPC GPN GRMN GS GWW HAL HAS HBAN HCA HD HIG HII
HLT HOLX HON HPE HPQ HRL HSIC HST HSY HUBB HUM HWM IBM ICE IDXX IEX
IFF ILMN INCY INTC INTU INVH IP IPG IQV IR IRM ISRG IT ITW IVZ J JBL
JCI JKHY JNJ JNPR JPM K KDP KHC KIM KLAC KMB KMI KMX KO KR KVUE L
LDOS LEN LH LHX LII LIN LKQ LLY LMT LNC LNT LOW LRCX LULU LUV LVS LW
LYB LYV MA MAA MAR MAS MCD MCHP MCK MCO MDLZ MDT MET META MGM MHK MKC
MKTX MLM MMC MMM MNST MO MOH MOS MPC MPWR MRK MRNA MRO MS MSFT MSI MTB
MTCH MTCH MTD MU NCLH NDAQ NDSN NEE NEM NFLX NI NKE NOC NOW NRG NSC
NTAP NTRS NUE NVDA NVR NWS NWSA NXPI O ODFL OKE OMC ON ORCL ORLY OTIS
OXY PANW PARA PAYC PAYX PCAR PCG PEG PEP PFE PFG PG PGR PH PHM PKG
PLD PLTR PM PNC PNR PNW PODD POOL PPG PPL PRU PSA PSX PTC PWR PX PYPL
QCOM QRVO RCL REG REGN RF RJF RL RMD ROK ROL ROP ROST RSG RTX RVTY
SBAC SBUX SCHW SCI SHW SJM SLB SMCI SNA SNPS SO SPG SPGI SRE STE STLD
STT STX STZ SW SWK SWKS SYF SYK SYY T TAP TDG TDY TECH TEL TER TFC TFX
TGT TJX TMO TMUS TPL TPR TRGP TRMB TROW TRV TSCO TSLA TSN TT TTWO TXN
TXT TYL UAL UBER UDR UHS ULTA UNH UNP UPS URI USB V VICI VLO VLTO VMC
VRSK VRSN VRTX VST VTR VTRS VZ WAB WAT WBD WDAY WDC WEC WELL WFC WM
WMB WMT WRB WST WTW WY WYNN XEL XOM XYL YUM ZBH ZBRA ZTS
"""

SP500 = {item.strip().upper() for item in _SP500_TEXT.split() if item.strip()}


def yahoo_symbol(symbol: str) -> str:
    return symbol.replace(" ", ".").upper().strip()


def ib_symbol(symbol: str) -> str:
    return yahoo_symbol(symbol).replace(".", " ")


def is_sp500(symbol: str) -> bool:
    return yahoo_symbol(symbol) in SP500
